spring:
  application:
    name: spring-bff
  security:
    oauth2:
      client:
        registration:
          keycloak: # registration id for the auth svc
            client-id: spring-angular-bff
            # local creds, nbd:
            client-secret: c0FGGZx5irkpRBqTnvZdQ3vgWZJ6L9U1
            authorization-grant-type: authorization_code
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/api/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost/auth/realms/spring-resource-users
            # rest of the URLs should be dynamically retrieved by spring
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: myuser
    password: mypassword
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

server:
  port: 8081
  forward-headers-strategy: native # Tomcat - doesn't handle X-Forwarded-Prefix
  # forward-headers-strategy: framework # Spring - handles that prefix

logging:
  level:
    org:
      springframework: INFO
