spring:
  application:
    name: spring-bff
  security:
    user:
      name: user1
      password: 123456
    oauth2:
      client:
        registration:
          keycloak:
            client-id: spring-angular-bff
            # local creds, nbd:
            client-secret: c0FGGZx5irkpRBqTnvZdQ3vgWZJ6L9U1
            authorization-grant-type: authorization_code
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/api/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost/auth/realms/spring-resource-users
            # rest of the URLs should be dynamically retrieved by spring

server:
  port: 8081
  forward-headers-strategy: native

logging:
  level:
    org:
      springframework: INFO
